define Device/midea_morr-qr011
  IMAGE_SIZE := 32448k
  DEVICE_VENDOR := MIDEA
  DEVICE_MODEL := MORR-QR011
  DEVICE_COMPAT_VERSION := 1.1
  DEVICE_PACKAGES := kmod-usb2 kmod-usb3
  SUPPORTED_DEVICES += mt7621
endef
TARGET_DEVICES += midea_morr-qr011