#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Build test-upload

on: 
  workflow_dispatch:
    inputs:
      target:
        description: 'target'
        required: true
        default: ''

env:
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  PPPOE_USERNAME: ${{ secrets.PPPOE_USERNAME }}
  PPPOE_PASSWD: ${{ secrets.PPPOE_PASSWD }}
  SCKEY: ${{ secrets.SCKEY }}
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  DOCKER_ID: ${{ secrets.DOCKER_ID }}
  DOCKER_PASSWD: ${{ secrets.DOCKER_PASSWD }}
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: Ubuntu-22.04
    name: Build ${{github.event.inputs.target}}
    strategy:
      fail-fast: false
      matrix:
        target: ["${{ github.event.inputs.target }}"]
    steps:
    - name: create
      run: |
        mkdir -p openwrt/bin/targets
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > openwrt/bin/targets/a.txt
        cat openwrt/bin/targets/a.txt
        sudo -E apt-get -qq install zip
        zip -r a.zip openwrt
    - name: Deploy imagebuilder to server
      uses: easingthemes/ssh-deploy@main
      continue-on-error: true
      if: env.SSH_PRIVATE_KEY && ! contains(github.event.action, 'noser')
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-avzr"
        SOURCE: a.zip
        REMOTE_HOST: '150.230.59.22'
        REMOTE_PORT: '3122'
        REMOTE_USER: root
        TARGET: "/opt/openwrt"
